version: "3"
services:
  mongo:
    image: mongo:4.2.14
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - recipe-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - recipe-network
networks:
  recipe-network:
    driver: bridge
