version: "3"
services:
  mongodb:
    container_name: mongodb
    image: mongo:4.2.14
    ports:
      - "27017:27017"
    restart: always
    networks:
      - recipe-network
    hostname: mongodb
    volumes:
      - ~/mongodata:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
    networks:
      - recipe-network
networks:
  recipe-network:
    driver: bridge
